// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO0tOKAlHjBHzfcA3tHNkfN4sxh7ktLa4',
    appId: '1:894963407698:web:4ec74103df4aa31e07f88b',
    messagingSenderId: '894963407698',
    projectId: 'chat-6647c',
    authDomain: 'chat-6647c.firebaseapp.com',
    storageBucket: 'chat-6647c.appspot.com',
    measurementId: 'G-5ZK11VVP44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo9mvjxkLKeiDhLQV_X7fuGdwMvyaT6PM',
    appId: '1:894963407698:android:4abdafcf444ef98707f88b',
    messagingSenderId: '894963407698',
    projectId: 'chat-6647c',
    storageBucket: 'chat-6647c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoxo9u8qWpiHwqol9bMG6pdQqTzVBrfk8',
    appId: '1:894963407698:ios:55e6dcc4aeab67c107f88b',
    messagingSenderId: '894963407698',
    projectId: 'chat-6647c',
    storageBucket: 'chat-6647c.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoxo9u8qWpiHwqol9bMG6pdQqTzVBrfk8',
    appId: '1:894963407698:ios:3a391c248a99db7207f88b',
    messagingSenderId: '894963407698',
    projectId: 'chat-6647c',
    storageBucket: 'chat-6647c.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
